# Generated by Django 4.0 on 2022-01-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owner',
            field=models.BooleanField(default=True),
        ),
    ]
